// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbnvgugqnreehwfkpucz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJibnZndWdxbnJlZWh3ZmtwdWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTc0OTEsImV4cCI6MjA2NTQ3MzQ5MX0.Mnvt2aKe3WSBUkcP0rS07nxV-PMj50yI-KKwk93lgtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);